pipeline
{
	agent any

	stages
	{
		stage('Checkout Code')
		{
			steps
			{
				git credentialsId: '87e66f55-a6ce-4b0f-a2b0-723d607dc227', url: 'https://github.com/heenasharma11/java_maven_CICD_app.git'
			}
		}
		stage('Build Code')
		{
			steps
			{
				sh 'mvn -Dmaven.test.failure.ignore clean package'
			}
		}
		stage('Test Code')
		{
			steps
			{
				sh 'mvn test'
			}
		}
		stage('Deploy')
		{
			steps
			{
				withCredentials([sshUserPrivateKey(credentialsId: '1e3022b7-7ab7-4c16-862e-606bdc67ab1b', keyFileVariable: 'keyFile')])
				{
					sh 'scp -o StrictHostKeyChecking=no -i ${keyFile} Sample_Pipeline_Job/target/java_maven_CICD_app.war ec2-user@34.219.192.247:/home/ec2-user/apache-tomcat-9.0.37/webapps/'
				}
			}
		}
	}
}
