pipeline
{
	agent any

	stages
	{
		stage('Checkout Code')
		{
			steps
			{
				checkout scm
			}
		}

		stage('Build Code')
		{
			steps
			{
				sh 'cd maven-project && mvn clean package'
			}
		}

		stage('Test Code')
		{
			steps
			{
				sh 'cd maven-project && mvn test'
			}
		}

		stage('Deploy Code')
		{
			steps
			{
				withCredentials([sshUserPrivateKey(credentialsId: 'my-ec2-instance-credentials', keyFileVariable: 'keyFile')])
				{
					sh 'scp -o StrictHostKeyChecking=no -i ${keyFile} maven-project/target/maven-project.war ec2-user@3.18.108.104:/home/ec2-user/apache-tomcat-9.0.37/webapps/'
				}
			}
		}
	}
}