pipeline
{
	agent any

	stages
	{
		stage('Checkout Code')
		{
			steps
			{
				git credentialsId: '5f7ea1fb-d023-48c3-8f16-7a2d7e055e9e', url: 'https://github.com/TanzeemAlam/jenkins-automation.git'
			}
		}
		stage('Build Code')
		{
			steps
			{
				sh 'cd maven-project && mvn -Dmaven.test.failure.ignore clean package'
			}
		}
		stage('Test Code')
		{
			steps
			{
				sh 'cd maven-project && mvn test'
			}
		}
		stage('Deploy')
		{
			steps
			{
				withCredentials([sshUserPrivateKey(credentialsId: '1e3022b7-7ab7-4c16-862e-606bdc67ab1b', keyFileVariable: 'keyFile')])
				{
					sh 'scp -o StrictHostKeyChecking=no -i ${keyFile} maven-project/target/maven-project.war ec2-user@34.219.192.247:/home/ec2-user/apache-tomcat-9.0.37/webapps/'
				}
			}
		}
	}
}
